project:
  type: website
  render:
    - index.qmd
    - "*/*.ipynb"
    - "drills/*.qmd"
    - "reference/*.qmd"
    - "!templates/"

website:
  title: "Vojtěch's Random Walk"
  sidebar:
    contents: auto

format:
  html:
    theme: cosmo
    toc: true
    code-fold: show
    html-math-method: katex

execute:
  enabled: true
